---
- name: Ensure dependencies are installed
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ dnf_packages }}'

- name: Install python packages
  ansible.builtin.pip:
    name: '{{ item }}'
    state: present
  loop: '{{ pip_packages }}'

- name: Copy tigera-operator file to remote
  ansible.builtin.copy:
    src: files/tigera-operator.yaml
    dest: ~/tigera-operator.yaml

- name: Kubeadm init cluster
  ansible.builtin.command: >
  kubeadm init 
    --pod-network-cidr="{{ pod_network_cidr }}" 
    --control-plane-endpoint="{{ control_plane_endpoint }}" 
    --apiserver-cert-extra-sans="{{ cert_extra_sans }}"

- name: Create a directory ~/.kube if it does not exist
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig file to .kube
  ansible.builtin.copy:
    remote_src: yes 
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config

- name: Kubectl create pod network CRD (1/2) - tigera-operator
  kubernetes.core.k8s:
    state: present
    src: ~/tigera-operator.yaml
    wait: yes

- name: Kubectl create pod network CRD (2/2) - calico-network
  kubernetes.core.k8s:
    state: present
    template: templates/calico.yaml.j2
    wait: yes

- name: Wait for master node to be ready
  command: kubectl wait --for=condition=Ready nodes --all --timeout=600s